# Generated by Django 5.0.4 on 2024-05-12 20:10

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('aciklama', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Otomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(error_messages={'unique': 'Bu otomat adı zaten kullanılmış.'}, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('aciklama', models.TextField(blank=True)),
                ('durum', models.BooleanField(default=True)),
                ('konum', models.CharField(max_length=200)),
                ('kapasite', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OtomatSira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira_harf', models.CharField(help_text='Sıra harf', max_length=1, verbose_name='Sıra Harf')),
                ('sira_no', models.PositiveIntegerField(default=1, help_text='Sıra numarası', verbose_name='Sıra')),
                ('durum', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('otomat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.otomat')),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('aciklama', models.TextField(blank=True)),
                ('durum', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='OtomatUrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otomat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.otomat')),
                ('sira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.otomatsira')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.urun')),
            ],
        ),
        migrations.CreateModel(
            name='UrunResim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.handle_upload_urun)),
                ('urun', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.urun')),
            ],
        ),
    ]
