# Generated by Django 5.0.4 on 2024-06-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otomatsira',
            name='durum',
            field=models.BooleanField(default=True),
        ),
    ]
